import type { NextPage } from 'next';
import Head from 'next/head';
import Link from 'next/link';
import { trpc } from '../utils/trpc';

const Home: NextPage = () => {
  const { data: products } = trpc.useQuery(['product.getAll']);

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container mx-auto flex min-h-screen flex-col items-center justify-center p-4">
        <h1 className="text-4xl font-bold text-gray-700">Welcome to our store!</h1>
        <p className="text-lg text-gray-600">The are the following products in the DB:</p>
        <ul className="flex flex-col gap-4 mt-4">
          {products?.map((product) => (
            <li key={product.id} className="flex flex-col gap-2">
              <span className="text-lg font-bold text-gray-700">{product.name}</span>
              <span className="text-sm text-gray-600">{product.description}</span>
              <Link href={`/product/${product.id}`}>
                <a className="text-sm text-violet-500 underline decoration-dotted underline-offset-2">View Product</a>
              </Link>
            </li>
          ))}
        </ul>
      </main>
    </>
  );
};

export default Home;

type TechnologyCardProps = {
  name: string;
  description: string;
  documentation: string;
};

const TechnologyCard = ({ name, description, documentation }: TechnologyCardProps) => {
  return (
    <section className="flex flex-col justify-center rounded border-2 border-gray-500 p-6 shadow-xl duration-500 motion-safe:hover:scale-105">
      <h2 className="text-lg text-gray-700">{name}</h2>
      <p className="text-sm text-gray-600">{description}</p>
      <a
        className="m-auto mt-3 w-fit text-sm text-violet-500 underline decoration-dotted underline-offset-2"
        href={documentation}
        target="_blank"
        rel="noreferrer"
      >
        Documentation
      </a>
    </section>
  );
};
