name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# this workflow will wait for a Vercel preview deployment to be ready 
# and then set the PLAYWRIGHT_TEST_BASE_URL environment variable to the preview url
jobs:
  test_setup:
    name: Test setup
    runs-on: ubuntu-latest
    outputs:
      preview_url: ${{ steps.waitForVercelPreviewDeployment.outputs.url }}
    steps:
      - name: Wait for Vercel Preview
        uses: patrickedqvist/wait-for-vercel-preview@v1.3.1
        id: waitForVercelPreviewDeployment
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          max_timeout: 300
      - run: "echo deployment url is ready: ${{ steps.waitForVercelPreviewDeployment.outputs.url }}" 

# then the e2e tests are run using playwright in a job that depends on the test_setup job
  tests_e2e:
    name: Run end-to-end tests
    runs-on: ubuntu-latest
    needs: test_setup
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '18.x'
      - name: Install dependencies
        run: npm ci
      - name: Install playwright browsers
        run: npx playwright install
      # set the DATABASE_URL environment variable to the database url secret
      - name: Set environment variables
        run: |
         if [ "${{ secrets.DATABASE_URL }}" != "" ]; then
           echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> $GITHUB_ENV
         else
           echo "DATABASE_URL=postgresql://postgres:postgres@localhost:5432/postgres" >> $GITHUB_ENV
         fi
      - name: Run tests
        run: timeout 300 npx playwright test || exit 1
        env:
          PLAYWRIGHT_TEST_BASE_URL: ${{ needs.test_setup.outputs.preview_url }}
          NODE_ENV: "test"
          # Github secret set in the repository settings
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          # the environment variables are set here so that they are available to the next job
          # fix the Invalid environment variables when running tests in playwright
          NEXT_PUBLIC_NEXTAUTH_URL: ${{ needs.test_setup.outputs.preview_url }}
          NEXT_PUBLIC_BANK_NAME: "My Bank"
          NEXT_PUBLIC_BANK_ACCOUNT_NAME: "Account Name"
          NEXT_PUBLIC_BANK_ACCOUNT_NUMBER: "1234567890"
          NEXT_PUBLIC_CONTACT_EMAIL: "contact@example.com"
          NEXT_PUBLIC_IG_URL: "https://www.instagram.com/example/"
          NEXT_PUBLIC_PHONE_NUMBER: "123-456-7890"
          NEXT_PUBLIC_BANK_ACCOUNT_CLABE: "123456789012345678"
          NEXT_PUBLIC_STORE_NAME: "My Store"
          NEXT_PUBLIC_STORE_ADDRESS: "123 Main St."
          NEXTAUTH_SECRET: "mocked_nextauth_secret"
          NEXTAUTH_URL: ${{ needs.test_setup.outputs.preview_url }}
          DISCORD_CLIENT_ID: "mocked_discord_client_id"
          DISCORD_CLIENT_SECRET: "mocked_discord_client_secret"
          GMAIL_APP_PASSWORD: "mocked_gmail_app_password"
          GMAIL_USERNAME: "mocked_gmail_username"
          ADMIN_EMAILS: "mocked_admin_emails"
